/*
 * DAB_500W_settings.h
 *
 *  Created on: 2025Äê2ÔÂ15ÈÕ
 *      Author: Admin
 */

#ifndef DAB_500W_SETTINGS_H_
#define DAB_500W_SETTINGS_H_

#ifndef ONE_NANO_SEC
#define ONE_NANO_SEC ((float32_t)0.000000001)
#endif
#ifndef TWO_RAISED_TO_THE_POWER_SIXTEEN
#define TWO_RAISED_TO_THE_POWER_SIXTEEN ((float32_t)65536.0)
#endif
#ifndef TWO_RAISED_TO_THE_POWER_EIGHT
#define TWO_RAISED_TO_THE_POWER_EIGHT ((float32_t)256.0)
#endif
#define DAB_PWMSYSCLOCK_FREQ_HZ   ((float32_t)120*1000000)
#define DAB_pwmFrequency_Hz ((float32_t)100*1000)

#define DAB_SDFM_FILTER_TYPE            3
#define DAB_SDFM_OSR                    64
#define DAB_SDFM_CMPSS_OSR              32
#define DAB_SDFM_PU_SCALE_FACTOR  (float32_t)(32.0f/(float32_t)((int32_t)DAB_SDFM_OSR*DAB_SDFM_OSR*DAB_SDFM_OSR))
#define DAB_SDFM_PU_SCALE_FACTOR1  (float32_t)(12.8f/(float32_t)((int32_t)DAB_SDFM_OSR*DAB_SDFM_OSR*DAB_SDFM_OSR))
#define GPIO_PROFILING1 41
#define GPIO_PROFILING1_SET GPIO_GPBSET_GPIO41
#define GPIO_PROFILING1_CLEAR GPIO_GPBCLEAR_GPIO41
#define GPIO_PROFILING1_PIN_CONFIG GPIO_41_GPIO41

#define GPIO_PROFILING2 47
#define GPIO_PROFILING2_SET GPIO_GPBSET_GPIO47
#define GPIO_PROFILING2_CLEAR GPIO_GPBCLEAR_GPIO47
#define GPIO_PROFILING2_PIN_CONFIG GPIO_47_GPIO47

#define GPIO_PROFILING3 59
#define GPIO_PROFILING3_SET GPIO_GPBSET_GPIO59
#define GPIO_PROFILING3_CLEAR GPIO_GPBCLEAR_GPIO59
#define GPIO_PROFILING3_PIN_CONFIG GPIO_59_GPIO59

#define GPIO_PROFILING4 32
#define GPIO_PROFILING4_SET GPIO_GPBSET_GPIO32
#define GPIO_PROFILING4_CLEAR GPIO_GPBCLEAR_GPIO32
#define GPIO_PROFILING4_PIN_CONFIG GPIO_32_GPIO32

#define GPIO_PROFILING5 33
#define GPIO_PROFILING5_SET GPIO_GPBSET_GPIO33
#define GPIO_PROFILING5_CLEAR GPIO_GPBCLEAR_GPIO33
#define GPIO_PROFILING5_PIN_CONFIG GPIO_33_GPIO33
#endif /* DAB_500W_SETTINGS_H_ */
